### PR TITLE
add ts[a:b]=v and del ts[a:b] logic

### PR DESCRIPTION
**Pull request by sdementen**
First draft to add interval setter and deleter (could not find direct meaning/sense for getter).

### CODE REVIEW

**Comment by sdementen** [comment]
When setting an interval on an empty timeseries like
```python
ts = TimeSeries()
ts[2:4]=1
```
it currently throws an error when calling iterperiods. Is this normal ? or should iterperiods return an empty iterator when nothing is defined yet ?

**Comment by stringertheory** [comment]
That's a good and tough question... my first thoughts about how `iterperiods` should behave are:
- For a timeseries with a default value, yield a single `(-inf, inf, default)` or `(domain.lower, domain.upper, default)` if there's a domain. That would be consistent with how it behaves when it's not empty.
- For an empty timeseries with using `default=EXTEND_BACK`, I could see either throwing an error or just having it be empty. @sdementen did you hit a use case where this happened? Which behavior would have been more useful? I can imagine some cases where I'd like it to error out (say, if I want the total duration of returned periods to be > 0) and other where I'd just want it to be empty.

**Comment by sdementen** [comment]
I hit the case when using "ts[2:4]=1" on an empty time series ;-).
(
Fundamentally and correct me if I have misunderstood, the TimeSeries represents a right-continuous stepwise function (https://en.wikipedia.org/wiki/Step_function and https://en.wikipedia.org/wiki/Continuous_function#Directional_and_semi-continuity) on a domain, domain that can be unbounded in either direction. As the focus is on timeseries and the time flows only in one direction, the left-continuous version is not that relevant ==> no need to add an option for this.

What is today called "measurements" (self._d) could may be called Points (to be less specific to traces of measurements). For instance, if I want to model someone's agenda (with 0 if he/she is free, 1 if he/she has a meeting), the "measurement" wording is a bit awkward in this concept. By the way, the ts[today@2h00, today@3h00] = 1 could then mean that someone is busy between 2h and 3h today.

A default value for a function is equivalent to having self._d = {domain.lower : default value}. And it may be simpler to do exactly that in the __init__ and not have specific code for the default (but not really sure as I did not go through the full code ... what is your feeling/intuition on this)? 

If having a default value is just setting a point on the leftmost bound (could  be -inf), then iterperiods is not a specific case anymore. Either it has some value (defaut) or the TimeSeries has nothing in self._d (no default and no values) and can be deemed as undefined (raise a ValueError)


If a default is set, it is equivalent to have

**Comment by sdementen** [comment]
On the "del ts[a:b]", I agree it is rather ambiguous ... It is indeed the equivalent of remove_measurements_from_interval (or maybe better remove_points_in_interval) as you describe. It does not set the default value, as the default value is better seen (see previous post) as the "original value" on domain.lower. On the include/exclude, I would rather assume all operations are on a right-continuous curve and so we operate on [a,b) (to keep a consistent interpretation of bounds across traces). 
The effect of a "del ts[a:b]" would be to change the value on [b, ...) to the value of ts[a-epsilon] which is quite consistent with the simple "del ts[a]" that will set the value on [a,...) to the value just before a ts[a-epsilon]

**Pull request merged**
